// <auto-generated />
using System;
using CandidateManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CandidateManagement.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250306152125_SeedingCandidate")]
    partial class SeedingCandidate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidateManagement.Infrastructure.Entity.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwqrNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelephoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9dd31215-c6d4-4914-aaa6-bb3b89cc4266"),
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@example.com",
                            Forename = "John",
                            Surname = "Smith",
                            SwqrNumber = "10012345",
                            TelephoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("c22c1268-5058-4a5c-ba95-5652adc0568b"),
                            DateOfBirth = new DateTime(1985, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.doe@example.com",
                            Forename = "Jane",
                            Surname = "Doe",
                            SwqrNumber = "10023456",
                            TelephoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = new Guid("605f0f3a-6e0c-4988-baf0-a26662ce5e07"),
                            DateOfBirth = new DateTime(1992, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.johnson@example.com",
                            Forename = "Michael",
                            Surname = "Johnson",
                            SwqrNumber = "10034567",
                            TelephoneNumber = "9876543210"
                        },
                        new
                        {
                            Id = new Guid("b792c860-0abe-476f-8b4d-62cd60bc1ee4"),
                            DateOfBirth = new DateTime(1988, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.davis@example.com",
                            Forename = "Emily",
                            Surname = "Davis",
                            SwqrNumber = "10045678",
                            TelephoneNumber = "5551234567"
                        },
                        new
                        {
                            Id = new Guid("49b60ef5-c5ac-46a0-a6f3-fd322e0fc005"),
                            DateOfBirth = new DateTime(1995, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.brown@example.com",
                            Forename = "Robert",
                            Surname = "Brown",
                            SwqrNumber = "10056789",
                            TelephoneNumber = "5559876543"
                        },
                        new
                        {
                            Id = new Guid("fea2e219-d087-46b4-a0fc-84d3a4236b38"),
                            DateOfBirth = new DateTime(1990, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.wilson@example.com",
                            Forename = "Sarah",
                            Surname = "Wilson",
                            SwqrNumber = "10067890",
                            TelephoneNumber = "4443217890"
                        },
                        new
                        {
                            Id = new Guid("95248028-958e-467d-9a44-d22105ee7d15"),
                            DateOfBirth = new DateTime(1987, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.martinez@example.com",
                            Forename = "David",
                            Surname = "Martinez",
                            SwqrNumber = "10078901",
                            TelephoneNumber = "3335671234"
                        },
                        new
                        {
                            Id = new Guid("8bf04c27-1139-43ce-933c-724c9ba967ab"),
                            DateOfBirth = new DateTime(1993, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.anderson@example.com",
                            Forename = "Laura",
                            Surname = "Anderson",
                            SwqrNumber = "10089012",
                            TelephoneNumber = "2226549876"
                        },
                        new
                        {
                            Id = new Guid("0ebf2035-e23e-421a-9c89-06ac9887891b"),
                            DateOfBirth = new DateTime(1989, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.taylor@example.com",
                            Forename = "James",
                            Surname = "Taylor",
                            SwqrNumber = "10190123",
                            TelephoneNumber = "1117896543"
                        },
                        new
                        {
                            Id = new Guid("22bd08f6-890f-401b-b415-4a6a64628612"),
                            DateOfBirth = new DateTime(1996, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olivia.harris@example.com",
                            Forename = "Olivia",
                            Surname = "Harris",
                            SwqrNumber = "10201234",
                            TelephoneNumber = "9991239876"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
